name: My first workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    job-name-print-hello-world:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - run: bash script.sh
        
    
  
